service: single-page-app-via-cloudfront7

frameworkVersion: "3"

plugins:
  - serverless-single-page-app-plugin

custom:
  s3Bucket: test-bucket-for-soi-vish

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

resources:
  Resources:
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal:
                AWS:
                  !Join
                    - ''
                    - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity '
                      - ${ssm:vishoai}
                # "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E1GZESU8DIIDT8"
              # '*'
                # CanonicalUser:
                #   Fn::GetAtt: [CloudFrontOAI, S3CanonicalUserId]
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.s3Bucket}.s3.amazonaws.com
              Id: WebApp
              S3OriginConfig:
                OriginAccessIdentity:
                  !Join
                    - ''
                    - - 'origin-access-identity/cloudfront/'
                      - ${ssm:vishoai}
                  # !Join [
                  #   "",
                  #   # E1GZESU8DIIDT8
                  #   # ["origin-access-identity/cloudfront/", !Ref CloudFrontOAI]
                  #   ["origin-access-identity/cloudfront/", ${ssm:vishoai}]
                  # ]
          Enabled: "true"
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: WebApp
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: "true"
    CloudFrontOAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "oaiexample1.s3.amazonaws.com"
    myAppSSMParameterName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: vishoai
        Type: String
        Value: 
          Ref: CloudFrontOAI

  Outputs:
  # CloudFrontOAI
    CloudFrontOAI:
      Value: 
        Ref: CloudFrontOAI

